require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WunschesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Wunsch. As you add validations to Wunsch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WunschesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all wunsches as @wunsches" do
      wunsch = Wunsch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:wunsches)).to eq([wunsch])
    end
  end

  describe "GET #show" do
    it "assigns the requested wunsch as @wunsch" do
      wunsch = Wunsch.create! valid_attributes
      get :show, {:id => wunsch.to_param}, valid_session
      expect(assigns(:wunsch)).to eq(wunsch)
    end
  end

  describe "GET #new" do
    it "assigns a new wunsch as @wunsch" do
      get :new, {}, valid_session
      expect(assigns(:wunsch)).to be_a_new(Wunsch)
    end
  end

  describe "GET #edit" do
    it "assigns the requested wunsch as @wunsch" do
      wunsch = Wunsch.create! valid_attributes
      get :edit, {:id => wunsch.to_param}, valid_session
      expect(assigns(:wunsch)).to eq(wunsch)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Wunsch" do
        expect {
          post :create, {:wunsch => valid_attributes}, valid_session
        }.to change(Wunsch, :count).by(1)
      end

      it "assigns a newly created wunsch as @wunsch" do
        post :create, {:wunsch => valid_attributes}, valid_session
        expect(assigns(:wunsch)).to be_a(Wunsch)
        expect(assigns(:wunsch)).to be_persisted
      end

      it "redirects to the created wunsch" do
        post :create, {:wunsch => valid_attributes}, valid_session
        expect(response).to redirect_to(Wunsch.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved wunsch as @wunsch" do
        post :create, {:wunsch => invalid_attributes}, valid_session
        expect(assigns(:wunsch)).to be_a_new(Wunsch)
      end

      it "re-renders the 'new' template" do
        post :create, {:wunsch => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wunsch" do
        wunsch = Wunsch.create! valid_attributes
        put :update, {:id => wunsch.to_param, :wunsch => new_attributes}, valid_session
        wunsch.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested wunsch as @wunsch" do
        wunsch = Wunsch.create! valid_attributes
        put :update, {:id => wunsch.to_param, :wunsch => valid_attributes}, valid_session
        expect(assigns(:wunsch)).to eq(wunsch)
      end

      it "redirects to the wunsch" do
        wunsch = Wunsch.create! valid_attributes
        put :update, {:id => wunsch.to_param, :wunsch => valid_attributes}, valid_session
        expect(response).to redirect_to(wunsch)
      end
    end

    context "with invalid params" do
      it "assigns the wunsch as @wunsch" do
        wunsch = Wunsch.create! valid_attributes
        put :update, {:id => wunsch.to_param, :wunsch => invalid_attributes}, valid_session
        expect(assigns(:wunsch)).to eq(wunsch)
      end

      it "re-renders the 'edit' template" do
        wunsch = Wunsch.create! valid_attributes
        put :update, {:id => wunsch.to_param, :wunsch => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested wunsch" do
      wunsch = Wunsch.create! valid_attributes
      expect {
        delete :destroy, {:id => wunsch.to_param}, valid_session
      }.to change(Wunsch, :count).by(-1)
    end

    it "redirects to the wunsches list" do
      wunsch = Wunsch.create! valid_attributes
      delete :destroy, {:id => wunsch.to_param}, valid_session
      expect(response).to redirect_to(wunsches_url)
    end
  end

end
